remote_theme: pmarsceill/just-the-docs

title: U4A2
color_scheme: dark
search_enabled: true
footer_content: "Analysis and Commentary by James Tauber (Yret, UDIC Ephesian Dragon) — follow @jtauber on <a href='https://twitter.com/jtauber'>Twitter</a> and <a href='https://github.com/jtauber'>GitHub</a>."
ga_tracking: UA-175899-18